name: shoes_app
description: A new Flutter project.

publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  provider: ^6.0.5
  http: ^1.0.0
  syncfusion_flutter_charts: ^28.1.39
  flutter_easyloading: ^3.0.5
  shared_preferences: ^2.0.15
  path_provider: ^2.0.14
  percent_indicator: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/bottom_bar_icon/
